'use client';
import {useRef,useState,type FormEvent} from 'react';
import type {LuxuryOrderSectionProps,CatalogSelection} from './order/order-types';
import {orderArt,DISTRICTS} from './order/order-art';
import {OrderImage} from './order/order-image';
import {OrderOtp} from './order/order-otp';
import './order/order.css';
const STEPS=['পণ্য নির্বাচন','ভ্যারিয়েন্ট নির্বাচন','পরিমাণ নির্বাচন','ডেলিভারি তথ্য','নিশ্চিতকরণ'];
const TITLES=['আপনার পছন্দের পণ্য নির্বাচন করুন','আপনার পছন্দের ভ্যারিয়েন্ট বেছে নিন','পরিমাণ নির্ধারণ করুন','ডেলিভারি তথ্য দিন','আপনার অর্ডার প্রস্তুত'];
const HINTS=['প্রথমে যে পণ্যটি অর্ডার করতে চান, সেটি বেছে নিন','আপনার পছন্দের রং ও ডিজাইন বেছে নিন','আপনার নির্বাচিত পণ্যের পরিমাণ নির্ধারণ করুন','আপনার অর্ডার পৌঁছে দিতে নিচের তথ্যগুলো সঠিকভাবে দিন','সব তথ্য ঠিক আছে কিনা দেখে অর্ডার নিশ্চিত করুন'];
const money=(n:number)=>'৳'+n.toLocaleString('bn-BD');
export function LuxuryOrderSection(props:LuxuryOrderSectionProps){
 const {catalogSelection:selection,catalogError='',catalogProducts,onCatalogSelectionChange,quantity,setQuantity,orderState,setOrderState,otpState,setOtpState,idempotencyKeyRef,submitOrder}=props;
 const [step,setStep]=useState(0),[customer,setCustomer]=useState<Record<string,string>>({}),[localError,setLocalError]=useState('');
 const form=useRef<HTMLFormElement>(null),heading=useRef<HTMLHeadingElement>(null),locked=useRef(false);
 const products=catalogProducts?.length?catalogProducts:selection?[{...selection.product,variants:selection.product.variants?.length?selection.product.variants:[selection.variant]}]:[];
 const product=products.find(p=>(p.id||p.slug||p.name)===(selection?.product.id||selection?.product.slug||selection?.product.name))||products[0];
 const variants=product?.variants||[];
 const amount=(selection?.variant.priceMinor||0)*quantity/100;
 const busy=orderState.status==='loading'||otpState.status==='sending'||otpState.status==='verifying';
 const completed=orderState.status==='success';
 const unavailable=!selection||!selection.variant.inStock||!!catalogError;
 const photo=selection?orderArt(selection.product,selection.variant.sku):'/niyamah/order/placeholder.svg';
 function go(next:number){setStep(next);setLocalError('');requestAnimationFrame(()=>{const h=heading.current;h?.focus({preventScroll:true});if(h&&h.getBoundingClientRect().top<70)h.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});}
 function clearError(){if(orderState.status==='error'){idempotencyKeyRef.current=null;setOrderState({status:'idle',message:'',publicId:'',preferencesUrl:''});}}
 function choose(next:CatalogSelection){if(busy||completed)return;if(onCatalogSelectionChange)onCatalogSelectionChange(next);else if(next.variant.sku!==selection?.variant.sku)return;setQuantity(1);idempotencyKeyRef.current=null;clearError();setLocalError('');}
 function count(next:number){setQuantity(Math.max(1,Math.min(5,next)));idempotencyKeyRef.current=null;clearError();}
 function next(){if(unavailable){setLocalError('অর্ডারের জন্য স্টকে থাকা একটি পণ্য নির্বাচন করুন।');return;}if(step===3){if(!form.current?.reportValidity())return;const phone=String(new FormData(form.current).get('phone')||'').replace(/[০-৯]/g,d=>String('০১২৩৪৫৬৭৮৯'.indexOf(d))).replace(/[\s()-]/g,'');if(!/^(?:\+?88)?01[3-9]\d{8}$/.test(phone)){setLocalError('সঠিক বাংলাদেশি মোবাইল নম্বর লিখুন।');form.current?.querySelector<HTMLInputElement>('[name="phone"]')?.focus();return;}}go(Math.min(4,step+1));}
 async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(step!==4){next();return;}if(busy||completed||locked.current||unavailable)return;locked.current=true;try{await submitOrder(e);}finally{locked.current=false;}}
 return <section id="order-section" className="no-section" lang="bn" data-track-section="order"><span id="order"/><div className="no-shell"><header className="no-brandbar"><div>NIYAMAH<small>ATTIRES</small></div><p>A SMALL CHOICE — A BIGGER PEACE</p></header>
 <nav className="no-steps" aria-label="Order progress">{STEPS.map((label,i)=><button type="button" key={label} disabled={i>step||busy||completed} onClick={()=>go(i)} aria-current={step===i?'step':undefined} className={i<=step?'is-done':''}><b>{i<step?'✓':i+1}</b><span>{label}</span></button>)}</nav>
 <form ref={form} id="order-form" onSubmit={onSubmit} onFocusCapture={()=>props.trackEventOnce('begin-checkout','BEGIN_CHECKOUT',selection,quantity)} onChange={e=>{const data=new FormData(e.currentTarget);setCustomer(Object.fromEntries(['name','phone','email','address','district','area'].map(k=>[k,String(data.get(k)||'')])));props.scheduleCheckoutRecoveryCapture(e.currentTarget);const target=e.target;if(target instanceof HTMLInputElement&&target.name==='phone'&&otpState.status!=='idle')setOtpState({status:'idle',challengeId:'',phone:'',code:'',token:'',message:'',devCode:''});clearError();}} data-clarity-mask="true">
 <div className={`no-panel ${step===0?'no-product-step':''}`}>
 {step>0&&<aside className="no-stage"><p>MODESTY<br/>IN EVERY<br/>MOMENT<span/></p><div className="no-arch"/><OrderImage src={photo} alt={selection?.product.name||''}/><div className="no-stone"/><div className="no-stage-info"><OrderImage src={photo}/><div><strong>{selection?.product.name}</strong><small>{selection?.variant.label||selection?.variant.sku}</small></div><div><small>Qty: {quantity}</small><strong>{money(amount)}</strong></div></div></aside>}
 <div className="no-content"><header className="no-title"><p>STEP {step+1} OF 5</p><h2 ref={heading} tabIndex={-1}>{completed?'আপনার অর্ডার সফল হয়েছে':TITLES[step]}</h2><span>{completed?'আমাদের সঙ্গে থাকার জন্য ধন্যবাদ।':HINTS[step]}</span></header>
 <fieldset disabled={busy||completed} className="no-fields">
 {step===0&&<div className="no-product-grid">{products.map(p=>{const selected=(p.id||p.slug||p.name)===(selection?.product.id||selection?.product.slug||selection?.product.name);const v=p.variants.find(v=>v.inStock)||p.variants[0];return <button type="button" key={p.id||p.slug||p.name} className={`no-choice ${selected?'is-selected':''}`} aria-pressed={selected} disabled={!v||!p.variants.some(v=>v.inStock)} onClick={()=>v&&choose({product:p,variant:v})}><div className="no-choice-art"><div className="no-card-arch"/><OrderImage src={orderArt(p,v?.sku)}/><i/></div><strong>{p.name}</strong><small>{p.variants.some(v=>v.inStock)?'আপনার প্রতিদিনের বিশেষ সঙ্গী':'বর্তমানে স্টকে নেই'}</small>{selected&&<b className="no-tick">✓</b>}</button>})}{!products.length&&<p className="no-empty">{catalogError||'পণ্যের তথ্য লোড হচ্ছে…'}</p>}</div>}
 {step===1&&<div className="no-variant-grid">{variants.map(v=><button type="button" key={v.sku} disabled={!v.inStock} aria-pressed={selection?.variant.sku===v.sku} className={`no-choice ${selection?.variant.sku===v.sku?'is-selected':''}`} onClick={()=>choose({product:product!,variant:v})}><OrderImage src={orderArt(product!,v.sku)}/><strong>{v.label||v.sku}</strong><small>{money(v.priceMinor/100)}{!v.inStock?' • স্টকে নেই':''}</small><b className="no-radio">{selection?.variant.sku===v.sku?'✓':''}</b></button>)}</div>}
 {step===2&&<><div className="no-quantity-card"><OrderImage src={photo}/><div><h3>{selection?.product.name}</h3><p>{selection?.variant.label||selection?.variant.sku}</p><button type="button" className="no-text-button" onClick={()=>go(1)}>ভ্যারিয়েন্ট পরিবর্তন ↗</button><label>পরিমাণ</label><div className="no-counter"><button type="button" onClick={()=>count(quantity-1)} disabled={quantity<=1} aria-label="পরিমাণ কমান">−</button><output>{quantity.toLocaleString('bn-BD')}</output><button type="button" onClick={()=>count(quantity+1)} disabled={quantity>=5} aria-label="পরিমাণ বাড়ান">+</button><small>{selection?.variant.inStock?'✓ স্টকে আছে':'স্টকে নেই'}</small></div></div><strong>{money(amount)}</strong></div><div className="no-totals"><p><span>পণ্যের মূল্য</span><strong>{money(amount)}</strong></p><p><span>ডেলিভারি চার্জ</span><strong>{money(0)}</strong></p><p><span>মোট পরিমাণ</span><strong>{money(amount)}</strong></p></div></>}
 <div hidden={step!==3} className="no-delivery"><div className="no-form-grid">
 <label>নাম <em>*</em><input name="name" autoComplete="name" required minLength={2} maxLength={255} placeholder="আপনার পূর্ণ নাম লিখুন"/></label>
 <label>মোবাইল নম্বর <em>*</em><input name="phone" type="tel" inputMode="tel" autoComplete="tel" required minLength={11} maxLength={18} placeholder="01XXXXXXXXX"/></label>
 <label className="no-wide">সম্পূর্ণ ঠিকানা <em>*</em><textarea name="address" autoComplete="street-address" required minLength={3} maxLength={1000} rows={2} placeholder="বাড়ি নং, রোড/এলাকা, গ্রাম/মহল্লা"/></label>
 <label>জেলা <em>*</em><input name="district" list="no-districts" autoComplete="address-level1" required minLength={2} maxLength={160} placeholder="জেলা নির্বাচন করুন"/><datalist id="no-districts">{DISTRICTS.map(d=><option key={d} value={d}/>)}</datalist></label>
 <label>উপজেলা / থানা <em>*</em><input name="area" autoComplete="address-level2" required minLength={2} maxLength={160} placeholder="উপজেলা / থানার নাম লিখুন"/></label>
 <label className="no-wide">ইমেইল <small>(ঐচ্ছিক)</small><input name="email" type="email" autoComplete="email" maxLength={255} placeholder="name@example.com"/></label></div>
 <div className="no-payment"><b>♧</b><div><strong>Cash on Delivery</strong><small>পণ্য হাতে পেয়ে টাকা পরিশোধ করুন</small></div><span>✓</span></div>
 <label className="no-consent"><input name="privacyAcknowledged" type="checkbox" required/><span>আমি <a href="/privacy" target="_blank" rel="noreferrer">গোপনীয়তা নীতি</a> পড়েছি এবং অর্ডার প্রসেসিং ও ডেলিভারির জন্য তথ্য ব্যবহারে সম্মত।</span></label>
 <details className="no-marketing"><summary>নতুন কালেকশন ও অফারের নোটিফিকেশন (ঐচ্ছিক)</summary>{[['emailMarketingConsent','Email'],['smsMarketingConsent','SMS'],['whatsappMarketingConsent','WhatsApp']].map(([name,label])=><label key={name}><input type="checkbox" name={name}/>{label}-এ অফার পেতে চাই</label>)}</details></div>
 {step===4&&<div className="no-confirm-grid"><div className="no-summary"><h3>অর্ডার সারাংশ<button type="button" onClick={()=>go(2)}>পরিবর্তন ↗</button></h3><dl><div><dt>পণ্য</dt><dd>{selection?.product.name}</dd></div><div><dt>ভ্যারিয়েন্ট</dt><dd>{selection?.variant.label||selection?.variant.sku}</dd></div><div><dt>পরিমাণ</dt><dd>{quantity}</dd></div><div><dt>ডেলিভারি পদ্ধতি</dt><dd>Cash on Delivery</dd></div><div><dt>ডেলিভারি চার্জ</dt><dd>{money(0)}</dd></div><div className="no-grand"><dt>মোট পরিশোধ</dt><dd>{money(amount)}</dd></div></dl></div><div className="no-summary"><h3>আপনার তথ্য<button type="button" onClick={()=>go(3)}>পরিবর্তন ↗</button></h3><dl>{[['name','নাম'],['phone','মোবাইল'],['address','ঠিকানা'],['district','জেলা'],['area','উপজেলা / থানা']].map(([k,label])=><div key={k}><dt>{label}</dt><dd>{customer[k]}</dd></div>)}</dl><p className="no-note">অর্ডার নিশ্চিত করতে মোবাইল নম্বর OTP দিয়ে যাচাই করতে হতে পারে।</p></div></div>}
 </fieldset>
 {step===4&&<OrderOtp {...props}/>}
 {(localError||catalogError||orderState.message)&&<div className="no-alert" role="status"><p>{localError||catalogError||orderState.message}</p>{orderState.publicId&&<strong>অর্ডার নম্বর: {orderState.publicId}</strong>}{orderState.preferencesUrl&&<a href={orderState.preferencesUrl}>মার্কেটিং পছন্দ পরিবর্তন করুন</a>}</div>}
 <div className="no-actions"><button type="button" className="no-back" onClick={()=>go(step-1)} disabled={step===0||busy||completed}>← পূর্ববর্তী</button>{step<4?<button type="button" className="no-next" onClick={e=>{e.preventDefault();next();}} disabled={unavailable||busy}>পরবর্তী ধাপ →</button>:<button type="submit" className="no-next" data-track-cta="order_submit" data-track-label="অর্ডার নিশ্চিত করুন" disabled={unavailable||busy||completed}>{completed?'অর্ডার সফল হয়েছে ✓':busy?'প্রক্রিয়া চলছে…':'অর্ডার নিশ্চিত করুন →'}</button>}</div>
 {step===4&&<p className="no-secure">♧ নিরাপদ ও নির্ভরযোগ্য অর্ডার প্রসেসিং</p>}</div></div></form><footer className="no-footer"><span>FAITH · COMFORT · MODESTY</span><p>❀ শালীনতায় শান্তির পথ</p></footer></div></section>;
}
